XCopy VideoOS.Platform.SDK.dll %1 /Y
XCopy VideoOS.Platform.SDK.Log.dll %1 /Y
XCopy LogServiceClientMW.dll %1 /Y
XCopy boost_regex-vc1*.dll %1 /Y
XCopy boost_serialization-vc1*.dll %1 /Y
XCopy boost_thread-vc1*.dll %1 /Y
XCopy icu*.dll %1 /Y
XCopy msvcp1*.dll %1 /Y
XCopy msvcr1*.dll %1 /Y
XCopy xerces-c*.dll %1 /Y
