XCopy VideoOS.Platform.SDK.dll %1 /Y
XCopy VideoOS.Platform.SDK.Log.dll %1 /Y
XCopy LogServiceClientMW.dll %1 /Y
XCopy boost_regex-vc100-mt-*.dll %1 /Y
XCopy boost_serialization-vc100-mt-*.dll %1 /Y
XCopy boost_thread-vc100-mt-*.dll %1 /Y
XCopy icu*.dll %1 /Y
XCopy msvcp100*.dll %1 /Y
XCopy msvcr100*.dll %1 /Y
XCopy xerces-c*.dll %1 /Y
XCopy VideoOS.Platform.dll %1 /Y
XCopy VideoOS.Utilities.dll %1 /Y
XCopy VideoOS.LogServer.Communication.dll %1 /Y
XCopy Autofac.dll %1 /Y
